package pacote;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import pacote.Engine;
import pacote.GameOver;


public class Tela extends javax.swing.JFrame {

    int opcao;
    
     public void close(){
        WindowEvent ev = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(ev);
    }
    
    public Tela() {
        initComponents();
        jProgressBar1.setValue(Engine.pablo.getLife());
        jProgressBar1.setStringPainted(true);  
        this.jProgressBar1.setForeground(Color.yellow);
    }
    
    public Tela(String s) {
        initComponents();
        jLabel1.setText(s);
        jProgressBar1.setValue(Engine.pablo.getLife());
        jProgressBar1.setStringPainted(true);  
        this.jProgressBar1.setForeground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("      ...");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButton1.setText("Bag");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jProgressBar1.setBackground(new java.awt.Color(102, 255, 204));
        jProgressBar1.setForeground(new java.awt.Color(51, 255, 51));
        jProgressBar1.setToolTipText("HP");
        jProgressBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flormenor.jpg"))); // NOI18N

        jLabel3.setText("HP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Engine.opcao++;
        jProgressBar1.setValue(Engine.pablo.getLife());
        jProgressBar1.setStringPainted(true);  
        this.jProgressBar1.setForeground(Color.yellow);
        //O SWITCH CASE FOI USADO APENAS PARA CONTROLAR O FLUXO DAS LABELS/TELAS
        switch(Engine.opcao){
            case 1:
                //titúlo que agora virou tutorial
                jLabel1.setText("Ajude Pablo a resolver as escolhas da vida.");
                break;
            case 2:
                //intro-"primeiro evento"
                jLabel1.setText(Engine.pal2);
                ImageIcon imagem;
                imagem = new ImageIcon(getClass().getResource("pablofome.jpg"));
                jButton2.(imagem);
                break;
            case 3:
                //primeira escolha(FICA OU TRILHA)
                Tela2 tela2 =  new Tela2(Engine.choice0,Engine.choice1);
                tela2.mudar("trilha2.jpg");
                tela2.setVisible(true);
                dispose();
                break;
            case 4:
                //segundo evento
                if(Tela2.zeroum ==1){
                    //ACHA BANANA
                    jLabel1.setText(Engine.ligadorS);
                    imagem = new ImageIcon(getClass().getResource("bananaac.jpg"));
                    jButton2.setIcon(imagem);
                }else{
                    Engine.pablo.setLife(0);
                    jLabel1.setText(Engine.eventoFinal0S);
                    GameOver dead = new GameOver();
                    dead.mudaTexto(Engine.eventoFinal0S);
                    dead.setVisible(true);
                    dispose();
                }
                break;
            case 5:
                //segunda escolha COMER OU GUARDAR
                Tela2 tela22 =  new Tela2(Engine.choice2,Engine.choice3);
                tela22.setVisible(true);
                tela22.mudar("bananaac.jpg");
                dispose();
                break;
            case 6:
                //terceiro evento-matando de fome
                if(Tela2.zeroum ==1){
                    GameOver dead = new GameOver();
                    dead.mudaTexto(Engine.c);
                    dead.setVisible(true);
                    dispose();
                   /* jLabel1.setText(Engine.c);
                    jLabel1.setText("Fome: -20 hp "+Engine.g);
                    Engine.pablo.takeDamage(20); */
                }else
                    jLabel1.setText(Engine.g);
                    jLabel2.setText("HP INIMIGO:" + (Engine.evil.getLife()));
                    imagem = new ImageIcon(getClass().getResource("malandro.jpg"));
                    jButton2.setIcon(imagem);
                break;
            case 7:
                //terceira escolha LUTAR OU FUGIR
                Tela2 tela23 =  new Tela2(Engine.choice4,Engine.choice5);
                tela23.setVisible(true);
                tela23.mudar("malandro.jpg");
                dispose();
                break;
            case 8://loop da luta
                int i = 0; 
                if(Tela2.zeroum == 0 && Engine.pablo.getLife() > 0){
                        jLabel2.setText("HP INIMIGO:" + (Engine.evil.getLife()));
                        while(Engine.evil.getLife() > 0){   
                        Engine.pablo.battle(Engine.evil);
                        jLabel2.setText("HP INIMIGO:" + (Engine.evil.getLife()));
                        System.out.println("tomou:"+Engine.evil.getAttack());
                        System.out.println("Ainda tem:"+Engine.pablo.getLife());
                        i++;
                        }
                        jLabel1.setText("Tomou "+(100 - Engine.pablo.getLife())+" de dano em "+ i + " turnos.");
                        imagem = new ImageIcon(getClass().getResource("malandramente.jpg"));
                        jButton2.setIcon(imagem);
                }else if(Tela2.zeroum == 1 && Engine.pablo.getLife() > 0){
                    i++;    
                    Engine.pablo.takeDamage(Engine.evil.getAttack());
                    jLabel1.setText(Engine.e);
                    Engine.opcao = 6;
                    imagem = new ImageIcon(getClass().getResource("fuga.jpg"));
                    jButton2.setIcon(imagem);
                    
                }else{
                    GameOver dead = new GameOver();
                    dead.mudaTexto(Engine.f);
                    dead.setVisible(true);
                    dispose();
                }
                break;
            case 9:
                break;
            case 10://relatorio da luta
                jLabel1.setText(Engine.d);
                imagem = new ImageIcon(getClass().getResource("malandramente.jpg"));
                jButton2.setIcon(imagem);
                break;
            case 11://escolha roubar ou n
                Tela2 tela24 =  new Tela2(Engine.choice6,Engine.choice7);
                tela24.setVisible(true);
                tela24.mudar("ai.jpg");
                dispose();
                break;
            case 12:// se roubou,aumenta banana
                if(Tela2.zeroum == 0){
                    Engine.banana.qtd++;
                }
                break;
            case 13://segue adiante
                jLabel1.setText(Engine.h);
                imagem = new ImageIcon(getClass().getResource("boss.jpg"));
                jButton2.setIcon(imagem);
                break;
            case 14:
                Tela2 tela25 =  new Tela2(Engine.choice8,Engine.choice9);
                tela25.setVisible(true);
                tela25.mudar("boss.jpg");
                dispose();
                break;
            case 15:
                int w = 0; 
               
                if(Tela2.zeroum == 0 && Engine.pablo.getLife() > 0){
                        jLabel2.setText("HP INIMIGO:" + (Engine.boss.getLife()));
                        while(Engine.boss.getLife() > 0 && Engine.pablo.getLife() > 0){   
                        Engine.pablo.battle(Engine.boss);
                        jLabel2.setText("HP INIMIGO:" + (Engine.boss.getLife()));
                        System.out.println("tomou:"+Engine.boss.getAttack());
                        System.out.println("Ainda tem:"+Engine.pablo.getLife());
                        w++;
                        }
                        jLabel1.setText("Tomou "+(100 - Engine.pablo.getLife())+" de dano em "+ w + " turnos.");
                        imagem = new ImageIcon(getClass().getResource("boss.jpg"));
                        jButton2.setIcon(imagem);
                }else if(Tela2.zeroum == 1 && Engine.pablo.getLife() > 0){
                    jLabel1.setText(Engine.j);
                     imagem = new ImageIcon(getClass().getResource("fuga2.jpg"));
                        jButton2.setIcon(imagem);
                }else{
                    GameOver dead = new GameOver();
                    dead.mudaTexto(Engine.f);
                    dead.setVisible(true);
                    dispose();
                }
                break;
            case 16:
                if(Engine.boss.getLife() < 1){
                    jLabel1.setText(Engine.eventoMeioS);
                    Engine.opcao = 8000;
                }else if(Engine.pablo.getLife()<1){
                    GameOver dead = new GameOver();
                    dead.mudaTexto(Engine.f);
                    dead.setVisible(true);
                    dispose();
                }
                else
                    jLabel1.setText("Pablo retorna ao ponto inicial.");
                    imagem = new ImageIcon(getClass().getResource("pablofome.jpg"));
                    jButton2.setIcon(imagem);
                break;
            case 17:
                jLabel1.setText("Pablo está preso em um loop temporal.");
                break;
            case 18:
                jLabel1.setText("(Culpa do programador)");
                break;
            case 19:
                jLabel1.setText("E agora Pablo está fadado a esse fim.");
                imagem = new ImageIcon(getClass().getResource("po2.jpg"));
                    jButton2.setIcon(imagem);
                break;
            case 20:
                jLabel1.setText("A vida é um ciclo de decisões.");
                break;
            case 21:
                jLabel1.setText("A vida não tem um sentido.");
                break;
            case 22:
                jLabel1.setText("Assim como esse jogo.");
                break;
            case 23:
                if(Engine.pablo.getLife()<1){
                    jLabel1.setText("Só que voce enfrentou o boss antes da hora.");
                    GameOver dead = new GameOver();
                    dead.mudaTexto(Engine.f);
                    dead.setVisible(true);
                    dispose();
                }
                
                break;
            case 24:
                //abrir opções de finalizar jogo ou continuar o loop.
                 Tela2 tela26 =  new Tela2(Engine.choice10,Engine.choice11);
                tela26.setVisible(true);
                tela26.mudar("po2.jpg");
                dispose();
                break;
            case 25:
                if(Tela2.zeroum == 0){
                    jLabel2.setText(Engine.choice10);
                    Engine.pablo.setAttack(Engine.pablo.getAttack() + 20);
                    Engine.opcao=1;
                }
                else{
                    close();
                }
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Menu bag = new Menu();
        bag.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela("START").setVisible(true);
            }
        });
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1.setText(Engine.pal);
    }
    
 
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
